/* Creates the "cisco_job1 to "cisco_job20 jobs *?

(1..20).each { num ->
  
    freeStyleJob("cisco_job$num") {
        description("cisco_job generated by seed job")
        label("Node1")
        logRotator {
            numToKeep 15
        }
        scm {
            git {
                remote {
                    github('cmangamm/Pipeline','https')
                }
                branch('master')
            }
        }
        steps {
            shell('echo "Hello,This is step section"')
        }
    }
}
