job("My_Pipeline_Job") {
    description("My_Pipeline_Job generated by seed job")
    label("master")
    logRotator {
        numToKeep 15
    }
    scm {
        git {
            remote {
                github('cmangamm/Pipeline','https')
            }
            branch('master')
        }
    }
    steps {
        shell('echo "Hello,This is step section")
    }
